# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!
use_modular_headers!

target 'RedBeatMachine' do

end

target 'RedBeatMachineTests' do

end

target 'RedBeatMachineUITests' do

end

